### ISSUE TITLE
The link to DataMeetAMD points to gnatih's Github profile

### ISSUE THREAD

**Issue by shravan91** [gnatih/openahmedabad.org#2]
![datameetamd](https://cloud.githubusercontent.com/assets/3190951/23831813/b9bdc8fc-0728-11e7-859e-4017cc2e9be5.JPG)

> Change this link to -> http://datameet.org/chapters/ahmedabad/

@gnatih

**Comment by gnatih** [comment]
Fixed this with the latest commit.
